# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('era', models.CharField(blank=True, max_length=50)),
                ('pos', models.CharField(blank=True, max_length=50)),
                ('act', models.BooleanField()),
                ('blurb', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
