# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gp', models.IntegerField(default=0)),
                ('ab', models.IntegerField(default=0)),
                ('pa', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('single', models.IntegerField(default=0)),
                ('two', models.IntegerField(default=0)),
                ('three', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('bb', models.IntegerField(default=0)),
                ('ibb', models.IntegerField(default=0)),
                ('so', models.IntegerField(default=0)),
                ('hbp', models.IntegerField(default=0)),
                ('sf', models.IntegerField(default=0)),
                ('sh', models.IntegerField(default=0)),
                ('gdp', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('ba', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('obp', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('slg', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('ops', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('iso', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('babip', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('ubr', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('wgdp', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('wsb', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('wrc', models.IntegerField(default=0)),
                ('wraa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('woba', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('wrcp', models.IntegerField(default=0)),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.Batter')),
            ],
        ),
    ]
