# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Statline',
        ),
    ]
