# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_auto_20161201_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statline',
            name='ops',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statline',
            name='wraa',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
