# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_auto_20161201_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batter',
            old_name='era',
            new_name='league',
        ),
        migrations.RemoveField(
            model_name='batter',
            name='act',
        ),
        migrations.AddField(
            model_name='batter',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batter',
            name='bleft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='bright',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='catch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='ci',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='mi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='outf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batter',
            name='rp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='second',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='short',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='sp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='team',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='batter',
            name='third',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='tright',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='util',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statline',
            name='avaga',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='bba',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='bbnine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='bbpercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='bs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='cg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='er',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='era',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='fip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='g',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='gs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='ha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='hld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='hra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='hrnine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='ibba',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='ip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='statline',
            name='k',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='kbb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='kbbpercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='knine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='kpercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='statline',
            name='l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='lob',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='statline',
            name='ra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='sho',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='sv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='tb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='tbf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='w',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statline',
            name='whip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statline',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
