# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0006_auto_20161208_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
