# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0008_auto_20170116_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batter',
            name='my_team',
            field=models.BooleanField(default=False),
        ),
    ]
